### ISSUE TITLE
Find a historical weather series

### ISSUE THREAD

**Issue by gustavocarvalho1002** [deeplearningunb/AIppointment#1]
We need to find a dataset/API/crawler of historical rain series of our dataset city, because it will be cool add another feature saying how was the weather on that appointment day.

**Comment by gustavocarvalho1002** [comment]
Link do inmet http://www.inmet.gov.br/portal/index.php?r=bdmep/bdmep

**Comment by gustavocarvalho1002** [comment]
API do climatempo: https://advisor.climatempo.com.br/

**Comment by gustavocarvalho1002** [comment]
We are going to use the data set that I was able to found on INMET ( http://www.inmet.gov.br/portal/index.php ) to get the average temperature for each specific day

**Comment by icarooliv** [comment]
![](https://media.giphy.com/media/yJFeycRK2DB4c/giphy.gif)
