### ISSUE TITLE
Find a medical appointment dataset

### ISSUE THREAD

**Issue by gustavocarvalho1002** [deeplearningunb/AIppointment#2]
We need to find a dataset that cointains information about medical appointments and useful details like appointment date and patient infos.

**Comment by icarooliv** [comment]
We found a dataset provided at Kaggle.  

Many people have already worked with this dataset and found some issues that we can try to solve. For example this dataset it's out of balance (only ~30% of patient missed the appointment). We can try sampling it and see what happens.
