### ISSUE TITLE
Write project documentation

### ISSUE THREAD

**Issue by icarooliv** [deeplearningunb/AIppointment#3]
We need to document all of our development process and describe things like:

- [x] What is this project? 

- Which problem are we trying to solve?
- How we found out about this problem?

- [x] Why is this project needed?

- Based on the exposed problem, how can we generate value from this? 

- [x] How we intend to solve this problem?

- Which tools and processes we used to make our solution.

- [x] Contributing
- If someone wants to contribute to this project, how can they do this?

**Comment by gustavocarvalho1002** [comment]
Is it going be in english? Or could i write in portuguese? @icarooliv

**Comment by icarooliv** [comment]
being honest it is kinda dumb writing here in english but let's keep it for the sake of consistency rofl

**Comment by icarooliv** [comment]
i already started some work at README.md by now I think it is fine keeping all there
