### ISSUE TITLE
Treat dataset

### ISSUE THREAD

**Issue by icarooliv** [deeplearningunb/AIppointment#4]
**Is your feature request related to a problem? Please describe.**
Our appointment dataset have some issues related to dates, columns names and also the need to merge with our weather dataset.

**Describe the solution you'd like**
We need to change some columns names, and merge weather and appointment datasets. Also remove some unused data and other stuff to prepare for feature scaling and encoding.

**Comment by gustavocarvalho1002** [comment]
What I've done:

1 - Treated all data in "Date" column in the appointment.csv and temperature.csv so it would have the following format -> YYYY-mm-dd 

2 - I merged both dataset into one -> **appointment_and_temperature.csv**
